### ISSUE TITLE
飞书过来的图片bug,不同图片变成一样的了

### ISSUE THREAD

**Issue by yuluoxingzhao** [b-yp/logseq-link-to-local#13]
![image](https://github.com/b-yp/logseq-link-to-local/assets/66147836/063c1b5d-2409-42e9-a9f7-85edf8b98c7a)
![image](https://github.com/b-yp/logseq-link-to-local/assets/66147836/29929423-331c-49f4-8494-e0cc7e457b0a)
![image](https://github.com/b-yp/logseq-link-to-local/assets/66147836/230848da-5029-4df5-bc44-eb61ae959490)
飞书过来的图片bug,不同图片变成一样的了
 是所有的图片都变成这个名称了对吧
另外小丑不行啊,
没办法查询搜索批量替换插件等
换个正常的字符吧...

**Comment by b-yp** [comment]
收到，小弟修复一下

**Comment by b-yp** [comment]
v 1.6.2 已修复
