### ISSUE TITLE
PDF extension is stripped 

### ISSUE THREAD

**Issue by alexdremov** [b-yp/logseq-link-to-local#18]
Hi! Thanks for your work!

When I try to download link like `https://arxiv.org/pdf/2306.00477v4.pdf`

The plugin loads it into file with name like `2303_2535_1_1701120353129.15647` (without pdf extension). Could you preserve extension of loaded files? Or even more advanced, deduce it from MIME type?

Also, some messages are in Chinese, which is unexpected as Logseq is English-primary.

**Comment by b-yp** [comment]
I will address this issue within the next day. Thank you for your feedback.

**Comment by alexdremov** [comment]
Thanks!

I've already addressed this issue as well as rewritten existing code. 

https://github.com/b-yp/logseq-link-to-local/pull/19

Feel free to comment it or reject it if there's too much changes
